### ISSUE TITLE
i’m not exactly sure what’s wrong but i keep getting this error on my phone no matter what browser app i use

### ISSUE THREAD

**Issue by AnkithJG** [Thysbelon/gbaconv-web#10]
i’m trying to convert my fire pokemon fire red gba file to a sav file so that i can play that save file on my ipad. here is the output im getting:

home/web_user/savedata.gba
127
0
0
234
36
255
174
81
105
154
filename: /home/web_user/savedata.gba

**Comment by Thysbelon** [comment]
Hello. There seems to be some confusion about file types.

A .gba file contains game data that can never be modified by the player. Sprites, music, and the overworld are in the .gba file.

A save file, which can be in a few different formats like .sav and .srm, contains your game progress. The pokemon in your party and boxes, the number of gym badges you have obtained, the name of your player character, and where in Kanto your player character is located are all stored in the save file.

**Comment by euan-forrester** [comment]
I was confused about this too for a while and told several users the same thing until I finally realized what the issue is: online emulators sometimes output their save state files with extensions like `.gba`, so I'm pretty sure that this is referring to one of those.

@AnkithJG you can use https://savefileconverter.com/#/online-emulators to convert that to a regular emulator save (be sure to perform an in-game save in the online emulator first, and only the in-game save can be converted). From there, you can use gbaconv-web to convert that to a VBA format if that's what you're looking for.

**Comment by Thysbelon** [comment]
Thank you @euan-forrester!
