### ISSUE TITLE
??? no work

### ISSUE THREAD

**Issue by Gygrfynhvfcddeft** [Thysbelon/gbaconv-web#11]
home/web_user/savedata.srm
255
255
255
255
255
255
255
255
255
255
filename: /home/web_user/savedata.srm
len: 131072
Detected save type: FLASH 1MBit
filename: home/web_user/savedata.sav
home/web_user/savedata.srm
255
255
255
255
255
255
255
255
255
255
filename: /home/web_user/savedata.srm
len: 131072
Detected save type: FLASH 1MBit
filename: home/web_user/savedata.sav

**Comment by Thysbelon** [comment]
I will try to assist you using the information you have posted; but in the future, _please_ describe your issue with **as much detail as possible** in order to make it easier for people to help you.

gbaconv-web is designed to only convert libretro VBA's srm files. I believe the file you have is _not_ a libretro VBA srm file, but a different kind of file that is also named srm by coincidence.

The reason I believe this is because all libretro VBA srm files have a length of 139264 bytes. Your file has a length of 131072 bytes.

I think your file may already be in the standard .sav format, just with a different file extension on its name.   
Please try to take your .srm file and rename it to change the file extension to .sav, then see if it works in whatever flashcart or emulator or save file editor you were initially trying to use.

If it doesn't work, then please tell me where you obtained your .srm file.

**Comment by Gygrfynhvfcddeft** [comment]
I got it off of webretro by binbashbanana

**Comment by Thysbelon** [comment]
I have confirmed that taking the srm file from webretro (mGBA core) and renaming it to .sav allows the file to be loaded into emulators that use the standard sav format. There is no need to use gbaconv-web for these webretro files.
